### ISSUE TITLE
A temp folder is inserted into rocker-compiler.conf when not building from a clean folder

### ISSUE THREAD

**Issue by gregopet** [etiennestuder/gradle-rocker-plugin#11]
I have a problem when Rocker templates are being rebuilt. I am attaching a Gradle 6.6.1 [application](https://publicstash.s3-us-west-1.amazonaws.com/possible-bug.tar.gz) in which I have to do the following to reproduce the bug:

`./gradlew compileRocker`

This produces a _build/rocker-hot-reload/main/rocker-compiler.conf_ file that contains the correct information, i.e.:

```
#rocker.output.dir
#Fri Sep 25 19:17:52 CEST 2020
rocker.class.dir=/home/gregor/tmp/possible-bug/build/rocker-hot-reload/main
rocker.option.extendsClass=com.fizzed.rocker.runtime.DefaultRockerTemplate
rocker.option.optimize=false
rocker.output.dir=/home/gregor/tmp/possible-bug/build/generated-src/rocker/main
rocker.option.targetCharset=UTF-8
rocker.template.dir=/home/gregor/tmp/possible-bug/src/main/kotlin/templates
rocker.option.combineAdjacentPlain=true
rocker.option.javaVersion=1.8
rocker.option.extendsModelClass=com.fizzed.rocker.runtime.DefaultRockerModel
rocker.option.markAsGenerated=false
```
..then I make a change to only one of the templates and I again run `./gradlew compileRocker`

The _rocker-compiler.conf_ now looks differently:

```
#rocker.output.dir
#Fri Sep 25 19:19:22 CEST 2020
rocker.class.dir=/home/gregor/tmp/possible-bug/build/rocker-hot-reload/main
rocker.option.extendsClass=com.fizzed.rocker.runtime.DefaultRockerTemplate
rocker.option.optimize=false
rocker.output.dir=/home/gregor/tmp/possible-bug/build/generated-src/rocker/main
rocker.option.targetCharset=UTF-8
rocker.template.dir=/home/gregor/tmp/possible-bug/build/tmp/compileRocker
rocker.option.combineAdjacentPlain=true
rocker.option.javaVersion=1.8
rocker.option.extendsModelClass=com.fizzed.rocker.runtime.DefaultRockerModel
rocker.option.markAsGenerated=false
```

The template folder had changed, it now points to a temporary folder. If I now run the app again, it will only monitor this temporary folder and won't detect any changes (since I'm not making them there).

I am guessing that the problem comes from the block starting at row 194 of _RockerCompile.java_ and that `executeRocker` accidentally overwrites `rocker-compiler.conf`, but I'm only guessing since I can't for the life of me get IDEA to stop on my breakpoints in the Gradle plugin.

**Comment by etiennestuder** [comment]
Good report. Thanks, @gregopet . I will take a look and get back to you.

**Comment by etiennestuder** [comment]
I'm able to reproduce the problem with a functional test. And I have a fix that I will push tomorrow.

What I don't understand is: why do you rerun Gradle between making template changes when you have 'optimize=false' Rocker will already detect the template changes without rerunning Gradle.

**Comment by gregopet** [comment]
Thank you for the fix & the plugin. Honestly, I don't know anymore (I'm on another project for a few days right now), but somehow it was constantly happening. I think it was actually caused by me stopping the server (because I had made a change to the backend code) and re-running it while also making some changes to a template. 

The most bothersome part was not knowing why it happened - after investigating the why & how I can now mostly avoid it :)

**Comment by etiennestuder** [comment]
Thanks for the insights, @gregopet . I will let you know in this thread once I release the fix version later today.

**Comment by etiennestuder** [comment]
Now fixed via this [commit](https://github.com/etiennestuder/gradle-rocker-plugin/commit/066ddc02a8afd385f28e11cd8fc219976fd8d68a).

A patch version 3.0.2 of the gradle-rocker-plugin has been released just now. It should show up in the [Gradle Plugin Portal](https://plugins.gradle.org/plugin/nu.studer.rocker) in a couple of hours.
