### ISSUE TITLE
can we pull rocker template from a remote repo ?

### ISSUE THREAD

**Issue by sandys** [etiennestuder/gradle-rocker-plugin#46]
kinda looking at your project as a fantastic replacement for https://github.com/gradle/gradle/issues/1686 

wondering if we can pull the rocker template remotely, so the user experience becomes
"gradle --init-script mystarter.gradle"

 and mystarter.gradle can have the rocker template in some github repo (github.com/myrepo/some.git/raw/template.rocker.raw)

it becomes a one-liner basically

**Comment by etiennestuder** [comment]
Thanks for the suggestion. I'll think about the declaration of remote templates.

**Comment by code-magician323** [comment]
@sandys good idea

**Comment by etiennestuder** [comment]
See the link below for inspiration and a self-contained example of how Gradle dependency managment can be used to download Rocker templates from a remote location. Maybe it helps.

https://github.com/etiennestuder/gradle-rocker-plugin/tree/master/example/remote_template

**Comment by sandys** [comment]
This is so super cool !
Thanks so much.

Could you mention here how to use it ? I'm a bit confused on the right way
to use it, etc.

**Comment by etiennestuder** [comment]
`./gradlew build` which will then apply the _remote_template.gradle_ file. That file does all the work. The comments explain what happens in detail.
