### ISSUE TITLE
Incremental build goes stale

### ISSUE THREAD

**Issue by nedtwigg** [etiennestuder/gradle-rocker-plugin#5]
I haven't been able to make a nice testcase, but it happens fairly often that the output templates get stale, and I have to run with `--rerun-tasks` to get it to work right.  I realize that's not super helpful without a testcase, feel free to just close.

Is there an easy way to disable incremental build on just the rocker task?  The problem with `--rerun-tasks` is it forces lots of slow tasks to rerun, but I'd really just like to treat the `compileRocker` task as always out-of-date.

**Comment by etiennestuder** [comment]
Hi @nedtwigg. I assume you are using the latest version of the plugin and a recent version of Gradle? We are using the plugin heavily and do not observe any issues.

What you can do is call `cleanCompileRocker` to clean the output of just the `compileRocker` task.

Feel free to reopen if you give more details on the issue.

**Comment by nedtwigg** [comment]
Sorry, shoulda provided versions.  `'nu.studer.rocker' version '0.3.1'` and gradle version `4.2.1`.  Of course that alone doesn't really help ;-).  If I figure out any useful hints about repro or cause I'll post here and reopen.

**Comment by nedtwigg** [comment]
I've got a reproducible testcase now:

- gradle 5.1
- 'nu.studer.rocker' version '0.3.1'

```gradle
rockerVersion = '1.2.0'
rocker {
	main {
		optimize = false
		templateDir = file('src/main/rocker')
		outputDir = file('src/main/rocker-generated')
		extendsClass = 'common.CustomRockerTemplate'
		extendsModelClass = 'common.CustomRockerModel'
	}
}
```

1. in input directory, have a bunch of `.rocker.html` files, and an `index.html`
2. run `./gradlew compileRocker`, all good
3. delete `index.html`
4. run `./gradlew compileRocker`, it deletes every compiled template
5. run `./gradlew compileRocker`, everything reports as up-to-date, but there are no compiled templates
6. restore the deleted `index.html`
7. run `./gradlew compileRocker`, get `Parsing 0 rocker template files`, still no compiled templates
8. change a single `blah.rocker.html`
9. run `./gradlew compileRocker`, get `Parsing 1 rocker template files`, now there's just 1 compiled template

**Comment by etiennestuder** [comment]
Hi @nedtwigg, thanks. I will take a look.

**Comment by nedtwigg** [comment]
Just confirmed this is still present in `0.4`.

**Comment by etiennestuder** [comment]
@nedtwigg Yes, that latest release does not intend your issue.

**Comment by etiennestuder** [comment]
@nedtwigg did you see this warning in the readme?

```
Warning: do not configure any of templateDir, outputDir, and classDir to point to the same directory or to a directory that also contains other content.
```

**Comment by nedtwigg** [comment]
Ahh, looks like user error :)  We have templates from our legacy system in the input folder, and they've been getting slowly converted one by one.  We're almost done, so it hasn't been happening to us as much recently, which is what made it easier to pinpoint the exact reproduction steps.
