### ISSUE TITLE
Add a Kotlin DSL example

### ISSUE THREAD

**Issue by radarsh** [etiennestuder/gradle-rocker-plugin#7]
Could you add a Kotlin DSL example for this plugin? I tried the main Gradle rocker plugin but can't get the incremental build to work. I am hoping this plugin wouldn't have such issues.

**Comment by etiennestuder** [comment]
See the [Examples](https://github.com/etiennestuder/gradle-rocker-plugin#examples) section of the README file for how to use the gradle-rocker-plugin with the Kotlin DSL.
